export enum AccessRole {
  ADMIN_FULL_ACCESS = 'ADMIN_FULL_ACCESS',
  ADMIN_REGISTERED_DATA = 'ADMIN_REGISTERED_DATA',
  ADMIN_REGISTERED_DATA_WITH_UPDATE = 'ADMIN_REGISTERED_DATA_WITH_UPDATE',
  ADMIN_STATISTICS = 'ADMIN_STATISTICS',
}
