name: CI - ftp - Step 3 - Deploy to ftp

on:
  workflow_run:
    workflows: ['CI - ftp - Step 2 - Build ftp-release']
    types: [completed]
    branches:
#      - 'release/ftp'
      - 'DISABLED/DISABLED_DISABLED_DISABLED'

jobs:
  deploy-to-ftp:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        ref: release/ftp
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        local-dir: ./docs/
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
          **/AAA_OLD_PAGE/**
